Product = XWorld
Type	= a
Include = ../Include ../Include/XWorld ../Include-Common/ModernLua++ ../Include-Common
Source	= *.cpp *.cc
LibDir	= ../Lib
Lib 	= ModernLua++ CloudAtlas Lua
Define 	= 

include ../makefile.template
