Product = ZoneCenter
Type	= exe
Include = ../Include ../Include-Common
Source	= *.cpp
LibDir	= ../Lib
Lib 	= XWorld ModernLua++ CloudAtlas SQLite Lua protobuf
Define 	= 

include ../makefile.template
